# Generated by Django 3.2.7 on 2023-08-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('tc', models.IntegerField()),
                ('plaka', models.CharField(max_length=11)),
                ('telefon', models.IntegerField()),
                ('piece', models.IntegerField()),
                ('tents', models.IntegerField()),
                ('depozito', models.CharField(max_length=5)),
                ('tip', models.CharField(max_length=25)),
            ],
        ),
    ]
