# Generated by Django 3.2.7 on 2023-08-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('müşteri', '0003_auto_20230829_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
