# Generated by Django 3.2.7 on 2023-08-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('müşteri', '0004_auto_20230829_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(),
        ),
    ]
